name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Bypass the masking
        env:
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: |
          echo "$TOKEN" | base64
