name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Leak the secret (on purpose, for learning)
        env:
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: echo "The token is $TOKEN"
